# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normal_cdf <- function(x) {
    .Call('cxx11test_normal_cdf', PACKAGE = 'cxx11test', x)
}

